---
functional:
  - Пользователь должен иметь возможность пройти регистрацию и авторизацию на сайте;
  - Пользователь должен успешно создавать игру;
  - Пользователь должен иметь возможность выбора уровня сложности задач;
  - Пользователь должен иметь возможность выставлять время игры;
  - Пользователь должен иметь возможность выбора игры по тегу или имени;
  - Пользователь должен иметь возможность общаться с другими зарегистрированными игроками в чате;
  - Пользователь должен иметь возможность видеть статистику своих игр и результаты предыдущих матчей;
  - Пользователь должен иметь возможность видеть свой рейтинг;
  - Пользователь должен иметь возможность выбора языка программирования для игры;
  - Пользователь должен иметь возможность приглашать друга по ссылке для совместной игры;
  - Пользователь должен получать очки, на основе которых строится рейтинг за неделю, месяц и за все время;
  - Задачи должны быть доступны на русском и английском языках;
  - Пользователь должен иметь возможность следить за ходом игры других пользователей;
  - Игра должна завершаться победой, проигрышем или сдачей игрока;
  
  - Завершенная игра должна быть доступна в записи.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы;
  - Сайт должен быть безопасным и защищать данные пользователя;
  - Сайт должен быть удобным на мобильном устройстве;
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров;
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit:
  - Соответствие законодательству;
  - Масштабируемость;
  - Локализация;
  - Интеграция;
  - Персонализация;
  - Интернационализация.